version: '3.8'

volumes:
  micro-dns-service:

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2600:1900:4020:cd9b:0:0:0:0/64"

x-service-ipv6: &service-ipv6
  networks:
    - ip6net
  user: "root"
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  volumes:
    - &micro-dns-service-volume micro-dns-service:/micro-dns-service

services:
  jnlp:
    <<: *service-ipv6
    container_name: jnlp
    build:
      dockerfile: Dockerfile.jnlp
    command:
      - "/bin/bash"
      - "-c"
      - |
        sh /var/jenkins_config/jenkins-agent
    environment:
      HOME: "/root"
    volumes:
      - *micro-dns-service-volume
      - /var/run:/var/run
      - /root/.docker:/root/.docker
      - /var/lib/docker:/var/lib/docker
      - /var/jenkins_config:/var/jenkins_config
      - /lib/modules:/lib/modules
  docker-daemon:
    <<: *service-ipv6
    container_name: docker-daemon
    build:
      dockerfile: Dockerfile.dind
    privileged: true
    command: dockerd
    expose:
      - "2375"
    volumes:
      - *micro-dns-service-volume
      - /var/run:/var/run
      - /root/.docker:/root/.docker
      - /lib/modules:/lib/modules